// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIH9rqvEhCkd4Q3WNamqS5oyHhooR11vU',
    appId: '1:511786526401:web:a49455ccb4faf55d56d640',
    messagingSenderId: '511786526401',
    projectId: 'playlisted-b5056',
    authDomain: 'playlisted-b5056.firebaseapp.com',
    storageBucket: 'playlisted-b5056.firebasestorage.app',
    measurementId: 'G-7F5SECL9XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtucp4r24jF3CALdnij7i_UQT5WYWOL4M',
    appId: '1:511786526401:android:6f1018f05c22686f56d640',
    messagingSenderId: '511786526401',
    projectId: 'playlisted-b5056',
    storageBucket: 'playlisted-b5056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfPzD56GrHojyYsjfCpjb6ZoUXz8H9zk',
    appId: '1:511786526401:ios:4f25fb8dd9a2b8f356d640',
    messagingSenderId: '511786526401',
    projectId: 'playlisted-b5056',
    storageBucket: 'playlisted-b5056.firebasestorage.app',
    iosBundleId: 'com.example.playlisted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTfPzD56GrHojyYsjfCpjb6ZoUXz8H9zk',
    appId: '1:511786526401:ios:4f25fb8dd9a2b8f356d640',
    messagingSenderId: '511786526401',
    projectId: 'playlisted-b5056',
    storageBucket: 'playlisted-b5056.firebasestorage.app',
    iosBundleId: 'com.example.playlisted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIH9rqvEhCkd4Q3WNamqS5oyHhooR11vU',
    appId: '1:511786526401:web:e8a0afccdd70871656d640',
    messagingSenderId: '511786526401',
    projectId: 'playlisted-b5056',
    authDomain: 'playlisted-b5056.firebaseapp.com',
    storageBucket: 'playlisted-b5056.firebasestorage.app',
    measurementId: 'G-GQV84WSXTM',
  );
}
